export type Subtitle = {
  time: number;
  text: {
    es: string;
    en: string;
    fr: string;
  };
};

export type Phrase = {
  id: number;
  category: 'Saludos' | 'Comida' | 'Cortesía' | 'General' |'Familia' | 'Colores' |'Numeros'|'Animales';
  iconName: string;
  quechua: string;
  pronunciation: string;
  translation: {
    es: string;
    en: string;
    fr: string;
  };
  audioSrc: string;
};

export const phrases: Phrase[] = [
  // --- SALUDOS ---
  { id: 1, category: 'Saludos', iconName: 'Hand', quechua: 'Allillanchu', pronunciation: 'a-lli-llan-chu', translation: { es: '¿Cómo estás?', en: 'How are you?', fr: 'Comment ça va ?' }, audioSrc: '/audio/allillanchu.mp3' },
  { id: 2, category: 'Saludos', iconName: 'Smile', quechua: 'Allillanmi', pronunciation: 'a-lli-llan-mi', translation: { es: 'Estoy bien', en: 'I am well', fr: 'Je vais bien' }, audioSrc: '/audio/allillanmi.mp3' },
  { id: 3, category: 'Saludos', iconName: 'UserRoundCheck', quechua: 'Rimaykullayki', pronunciation: 'ri-may-ku-llay-ki', translation: { es: 'Disculpa / Permiso', en: 'Excuse me / Permission', fr: 'Excusez-moi / Permission' }, audioSrc: '/audio/rimaykullayki.mp3' },
  { id: 5, category: 'Saludos', iconName: 'History', quechua: 'Tupananchiskama', pronunciation: 'tu-pa-nan-chis-ka-ma', translation: { es: 'Hasta luego', en: 'See you later', fr: 'À plus tard' }, audioSrc: '/audio/tupananchiskama.mp3' },
  { id: 8, category: 'Saludos', iconName: 'Moon', quechua: 'Allin Tuta', pronunciation: 'a-llin tu-ta', translation: { es: 'Buenas Noches', en: 'Good Evening', fr: 'Bonsoir' }, audioSrc: '/audio/allinTuta.mp3' },
  { id: 19, category: 'Saludos', iconName: 'CircleHelp', quechua: '¿Imaynallan?', pronunciation: 'i-mai-na-llan', translation: { es: '¿Cómo estás?', en: 'How are you?', fr: 'Comment vas-tu ?' }, audioSrc: '/audio/imaynallan.mp3' },
  { id: 20, category: 'Saludos', iconName: 'Sun', quechua: 'Allin p\'unchay', pronunciation: 'a-llin Pun-chai', translation: { es: 'Buen día', en: 'Good day', fr: 'Bonne journée' }, audioSrc: '/audio/allinPunchay.mp3' },
  { id: 21, category: 'Saludos', iconName: 'Clock', quechua: 'Allin Sukha', pronunciation: 'a-llin su-kja', translation: { es: 'Buenas Tardes', en: 'Good afternoon', fr: 'Bon après-midi' }, audioSrc: '/audio/allinSukha.mp3' },
  
  // --- COMIDA ---
  { id: 6, category: 'Comida', iconName: 'Utensils', quechua: 'Mijuy', pronunciation: 'mi-jui', translation: { es: 'Comida', en: 'Food', fr: 'Nourriture' }, audioSrc: '/audio/mikuy.mp3' },
  { id: 7, category: 'Comida', iconName: 'Droplets', quechua: 'Unu', pronunciation: 'u-nu', translation: { es: 'Agua', en: 'Water', fr: 'Eau' }, audioSrc: '/audio/unu.mp3' },
  { id: 9, category: 'Comida', iconName: 'Banknote', quechua: 'Hayk\'an?', pronunciation: 'jai-kan', translation: { es: '¿Cuánto es?', en: 'How much is it?', fr: 'Combien ça coûte ?' }, audioSrc: '/audio/haykan.mp3' },

  // --- CORTESÍA ---
  { id: 10, category: 'Cortesía', iconName: 'Heart', quechua: 'Sumaq', pronunciation: 'su-mak', translation: { es: 'Delicioso', en: 'Delicious', fr: 'Délicieux' }, audioSrc: '/audio/sumak.mp3' },
  { id: 11, category: 'Cortesía', iconName: 'Zap', quechua: 'Atiq', pronunciation: 'a-tik', translation: { es: 'Valiente / Fuerte', en: 'Brave / Strong', fr: 'Courageux / Fort' }, audioSrc: '/audio/atiq.mp3' },
  { id: 12, category: 'Cortesía', iconName: 'Smile', quechua: 'Kusi', pronunciation: 'ku-si', translation: { es: 'Feliz / Alegre', en: 'Happy / Joyful', fr: 'Heureux / Joyeux' }, audioSrc: '/audio/kusi.mp3' },
  { id: 13, category: 'Cortesía', iconName: 'Heart', quechua: 'Munay', pronunciation: 'mu-nai', translation: { es: 'Hermosa/ hermoso', en: 'Cute/beautiful', fr: 'Beau / Belle' }, audioSrc: '/audio/munay.mp3' },

  // --- GENERAL ---
  { id: 14, category: 'General', iconName: 'MapPin', quechua: '¿Maypin?', pronunciation: 'mai-pin', translation: { es: '¿Dónde está?', en: "Where is it?", fr: 'Où est-ce ?' }, audioSrc: '/audio/maypin.mp3' },
  { id: 15, category: 'General', iconName: 'LifeBuoy', quechua: 'Yanapaway', pronunciation: 'ya-na-pa-wai', translation: { es: 'Ayúdame', en: 'Help me', fr: 'Aidez-moi' }, audioSrc: '/audio/yanapaway.mp3' },
  { id: 16, category: 'General', iconName: 'CircleHelp', quechua: 'Manan', pronunciation: 'Ma-nan', translation: { es: 'No', en: "No", fr: 'Non' }, audioSrc: '/audio/manan.mp3' },
  { id: 17, category: 'General', iconName: 'CheckCircle2', quechua: 'Ari', pronunciation: 'a-Ri', translation: { es: 'Sí', en: 'Yes', fr: 'Oui' }, audioSrc: '/audio/ari.mp3' },
  { id: 18, category: 'General', iconName: 'XCircle', quechua: 'Manan', pronunciation: 'Ma-nan', translation: { es: 'No', en: 'No', fr: 'Non' }, audioSrc: '/audio/manan.mp3' },
  { id: 30, category: 'General', iconName: 'Activity', quechua: 'Nanay', pronunciation: 'na-nai', translation: { es: 'Doler', en: 'Pain', fr: 'Douleur' }, audioSrc: '/audio/nanay.mp3' },

  // --- FAMILIA ---
  { id: 22, category: 'Familia', iconName: 'User', quechua: 'Taytay', pronunciation: 'tai-tai', translation: { es: 'Papá', en: 'Father', fr: 'Père' }, audioSrc: '/audio/taytay.mp3' },
  { id: 23, category: 'Familia', iconName: 'User', quechua: 'Mamay', pronunciation: 'ma-mai', translation: { es: 'Mamá', en: 'Mother', fr: 'Mère' }, audioSrc: '/audio/mamay.mp3' },
  { id: 26, category: 'Familia', iconName: 'User', quechua: 'Churi', pronunciation: 'chu-ri', translation: { es: 'Hijo (por el padre)', en: 'Son (by father)', fr: 'Fils (par le père)' }, audioSrc: '/audio/churi.mp3' },
  { id: 27, category: 'Familia', iconName: 'User', quechua: 'Ususi', pronunciation: 'u-su-si', translation: { es: 'Hija (por el padre)', en: 'Daughter (by father)', fr: 'Fille (par le père)' }, audioSrc: '/audio/ususi.mp3' },
  { id: 28, category: 'Familia', iconName: 'Baby', quechua: 'Wawa', pronunciation: 'wa-wa', translation: { es: 'Bebé / Niño/a', en: 'Baby / Child', fr: 'Bébé / Enfant' }, audioSrc: '/audio/wawa.mp3' },
  { id: 29, category: 'Familia', iconName: 'User', quechua: 'Awki', pronunciation: 'au-ki', translation: { es: 'Abuelo', en: 'Grandfather', fr: 'Grand-père' }, audioSrc: '/audio/awki.mp3' },
  { id: 36, category: 'Familia', iconName: 'User', quechua: 'Wayqey', pronunciation: 'wai-qei', translation: { es: 'Hermano (entre hombres)', en: 'Brother (man to man)', fr: 'Frère (entre hommes)' }, audioSrc: '/audio/wayqey.mp3' },
  { id: 37, category: 'Familia', iconName: 'Users', quechua: 'Ñaña', pronunciation: 'ña-ña', translation: { es: 'Hermana (entre mujeres)', en: 'Sister (woman to woman)', fr: 'Sœur (entre femmes)' }, audioSrc: '/audio/ñañay.mp3' },
  { id: 38, category: 'Familia', iconName: 'Users', quechua: 'Panay', pronunciation: 'pa-nai', translation: { es: 'Hermana (por el hombre)', en: 'Sister (by man)', fr: 'Sœur (par l\'homme)' }, audioSrc: '/audio/panay.mp3' },
  { id: 39, category: 'Familia', iconName: 'User', quechua: 'Tura', pronunciation: 'tu-ra', translation: { es: 'Hermano (por la mujer)', en: 'Brother (by woman)', fr: 'Frère (par la femme)' }, audioSrc: '/audio/turay.mp3' },

  // --- COLORES ---
  { id: 24, category: 'Colores', iconName: 'Circle', quechua: 'Puka', pronunciation: 'pu-ka', translation: { es: 'Rojo', en: 'Red', fr: 'Rouge' }, audioSrc: '/audio/puka.mp3' },
  { id: 25, category: 'Colores', iconName: 'Circle', quechua: 'Q\'ello', pronunciation: 'qe-llo', translation: { es: 'Amarillo', en: 'Yellow', fr: 'Jaune' }, audioSrc: '/audio/qello.mp3' },
  { id: 31, category: 'Colores', iconName: 'Circle', quechua: 'Yana', pronunciation: 'ya-na', translation: { es: 'Negro', en: 'Black', fr: 'Noir' }, audioSrc: '/audio/yana.mp3' },
  { id: 32, category: 'Colores', iconName: 'Circle', quechua: 'Yuraq', pronunciation: 'yu-rak', translation: { es: 'Blanco', en: 'White', fr: 'Blanc' }, audioSrc: '/audio/yuraq.mp3' },
  { id: 33, category: 'Colores', iconName: 'Circle', quechua: 'Anqas', pronunciation: 'an-kas', translation: { es: 'Azul', en: 'Blue', fr: 'Bleu' }, audioSrc: '/audio/anqas.mp3' },
  { id: 34, category: 'Colores', iconName: 'Circle', quechua: 'Q\'umir', pronunciation: 'ku-mir', translation: { es: 'Verde', en: 'Green', fr: 'Vert' }, audioSrc: '/audio/qumir.mp3' },
  { id: 35, category: 'Colores', iconName: 'Circle', quechua: 'Oq\'e', pronunciation: 'o-qe', translation: { es: 'Marrón / Plomo', en: 'Brown / Grey', fr: 'Marron / Gris' }, audioSrc: '/audio/oqhe.mp3' },
  { id: 40, category: 'Colores', iconName: 'Circle', quechua: 'Kulli', pronunciation: 'ku-lli', translation: { es: 'Morado', en: 'Purple', fr: 'Violet' }, audioSrc: '/audio/kulli.mp3' },

  // --- NÚMEROS ---
  { id: 41, category: 'Numeros', iconName: 'Hash', quechua: 'Huk', pronunciation: 'huk', translation: { es: 'Uno', en: 'One', fr: 'Un' }, audioSrc: '/audio/huk.mp3' },
  { id: 42, category: 'Numeros', iconName: 'Hash', quechua: 'Iskay', pronunciation: 'is-kai', translation: { es: 'Dos', en: 'Two', fr: 'Deux' }, audioSrc: '/audio/iskay.mp3' },
  { id: 43, category: 'Numeros', iconName: 'Hash', quechua: 'Kinsa', pronunciation: 'kin-sa', translation: { es: 'Tres', en: 'Three', fr: 'Trois' }, audioSrc: '/audio/kinsa.mp3' },
  { id: 44, category: 'Numeros', iconName: 'Hash', quechua: 'Tawa', pronunciation: 'ta-wa', translation: { es: 'Cuatro', en: 'Four', fr: 'Quatre' }, audioSrc: '/audio/tawa.mp3' },
  { id: 45, category: 'Numeros', iconName: 'Hash', quechua: 'Pichqa', pronunciation: 'pich-qa', translation: { es: 'Cinco', en: 'Five', fr: 'Cinq' }, audioSrc: '/audio/pichqa.mp3' },
  { id: 46, category: 'Numeros', iconName: 'Hash', quechua: 'Chunka', pronunciation: 'chun-ka', translation: { es: 'Diez', en: 'Ten', fr: 'Dix' }, audioSrc: '/audio/chunka.mp3' },

  // --- ANIMALES ---
  { id: 47, category: 'Animales', iconName: 'Dog', quechua: 'Allqo', pronunciation: 'all-qo', translation: { es: 'Perro', en: 'Dog', fr: 'Chien' }, audioSrc: '/audio/allqo.mp3' },
  { id: 48, category: 'Animales', iconName: 'Cat', quechua: 'Misi', pronunciation: 'mi-si', translation: { es: 'Gato', en: 'Cat', fr: 'Chat' }, audioSrc: '/audio/michi.mp3' },
  { id: 49, category: 'Animales', iconName: 'PawPrint', quechua: 'Kawallu', pronunciation: 'ka-wa-llu', translation: { es: 'Caballo', en: 'Horse', fr: 'Cheval' }, audioSrc: '/audio/kawallu.mp3' },

  // --- CORTESÍA / GENERAL ADICIONAL ---
  { id: 4, category: 'General', iconName: 'CircleHelp', quechua: '¿Imataq sutiyki?', pronunciation: 'i-ma-tak su-ti-i-ki', translation: { es: '¿Cuál es tu nombre?', en: 'What is your name?', fr: 'Quel est ton nom ?' }, audioSrc: '/audio/imataqsutiyki.mp3' },
  { id: 50, category: 'Cortesía', iconName: 'Heart', quechua: 'Sulpayki', pronunciation: 'sul-pai-ki', translation: { es: 'Gracias', en: 'Thank you', fr: 'Merci' }, audioSrc: '/audio/sulpayki.mp3' },
  { id: 51, category: 'Cortesía', iconName: 'MessageSquarePlus', quechua: 'Ama hinachu kay', pronunciation: 'a-ma hi-na-chu kai', translation: { es: 'Por favor', en: 'Please', fr: 'S\'il vous plaît' }, audioSrc: '/audio/amahinachukay.mp3' },
];

export const phraseCategories = ['Todo', ...Array.from(new Set(phrases.map(p => p.category)))];


export type MusicVideo = {
  id: number;
  youtubeId: string;
  title: string;
  artist: string;
  languages: string;
  startTime?: number;
  endTime?: number;
  subtitles?: Subtitle[];
};

export const musicVideos: MusicVideo[] = [
  { id: 1, youtubeId: 'viPKKHGdwHQ', title: 'Carnaval Despedida (Sub)', artist: 'Roger Chino', languages: 'Quechua', startTime: 5, subtitles: [
    { time: 48, text: { es: '¿A dónde estás yendo? (bis)', en: 'Where are you going? (repeat)', fr: 'Où vas-tu ? (bis)' } },
    { time: 51, text: { es: 'Regresa, hermanita', en: 'Come back, little sister', fr: 'Reviens, petite sœur' } },
    { time: 54, text: { es: 'No te vayas (bis)', en: 'Don’t go (repeat)', fr: 'Ne pars pas (bis)' } },
    { time: 57, text: { es: 'Vamos a bailar todavía', en: 'Let’s keep dancing', fr: 'Nous allons encore danser' } },
    { time: 60, text: { es: '¿A dónde estás yendo? (bis)', en: 'Where are you going? (repeat)', fr: 'Où vas-tu ? (bis)' } },
    { time: 63, text: { es: 'Regresa, hermanita', en: 'Come back, little sister', fr: 'Reviens, petite sœur' } },
    { time: 66, text: { es: 'No te vayas (bis)', en: 'Don’t go (repeat)', fr: 'Ne pars pas (bis)' } },
    { time: 69, text: { es: 'Vamos a bailar todavía', en: 'Let’s keep dancing', fr: 'Nous allons encore danser' } },
    { time: 72, text: { es: 'Ven pues, hermanita', en: 'Come along, little sister', fr: 'Viens donc, petite sœur' } },
    { time: 74, text: { es: 'Ponte frente a mí', en: 'Stand in front of me', fr: 'Mets-toi devant moi' } },
    { time: 77, text: { es: 'Este es nuestro traguito', en: 'This is our little drink', fr: 'C\'est notre petit verre' } },
    { time: 78, text: { es: 'Vamos a tomar', en: 'Let’s have a drink', fr: 'Allons boire' } },
    { time: 81, text: { es: 'Baila, soltera', en: 'Dance, single girl', fr: 'Danse, célibataire' } },
    { time: 83, text: { es: 'Sin avergonzarce', en: 'Without shame', fr: 'Sans honte' } },
    { time: 86, text: { es: 'En esta hermosa fiesta', en: 'At this beautiful celebration', fr: 'Dans cette belle fête' } },
    { time: 88, text: { es: 'Vamos a bailar', en: 'Let’s dance', fr: 'Allons danser' } },
    { time: 90, text: { es: '¿Qué queriendo me estás cantando?', en: 'Why are you singing to me like that?', fr: 'Que veux-tu en me chantant ainsi ?' } },
    { time: 94, text: { es: 'Jovencito caneño', en: 'Young man from Canas', fr: 'Jeune homme de Canas' } },
    { time: 96, text: { es: '¿Qué diciendo te me estarás riendo?', en: 'Why are you laughing at me like that?', fr: 'Que dis-tu en te moquant de moi ?' } },
    { time: 100, text: { es: 'Oye, atrevido jovencito', en: 'Hey, you daring young man', fr: 'Hé, jeune homme audacieux' } },
    { time: 102, text: { es: '¿Qué queriendo me estás cantando?', en: 'Why are you singing to me like that?', fr: 'Que veux-tu en me chantant ainsi ?' } },
    { time: 106, text: { es: 'Jovencito caneño', en: 'Young man from Canas', fr: 'Jeune homme de Canas' } },
    { time: 108, text: { es: '¿Qué diciendo te me estarás riendo?', en: 'Why are you laughing at me like that?', fr: 'Que dis-tu en te moquant de moi ?' } },
    { time: 112, text: { es: 'Oye, atrevido jovencito', en: 'Hey, you daring young man', fr: 'Hé, jeune homme audacieux' } },
    { time: 114, text: { es: 'Tenías tu mujer', en: 'You already had your woman', fr: 'Tu avais ta femme' } },
    { time: 116, text: { es: 'Me había fijado', en: 'I had noticed', fr: 'Je l\'avais remarqué' } },
    { time: 118, text: { es: 'Conóceme bien', en: 'Get to know me well', fr: 'Connais-moi bien' } },
    { time: 121, text: { es: 'Quién soy yo', en: 'Who I am', fr: 'Qui je suis' } },
    { time: 123, text: { es: 'Yo soy solterita', en: 'I am a single girl', fr: 'Je suis célibataire' } },
    { time: 125, text: { es: 'Amor enterita', en: 'With a whole heart for love', fr: 'Amour tout entière' } },
    { time: 128, text: { es: 'Muchacha bonita', en: 'Pretty young woman', fr: 'Jolie fille' } },
    { time: 130, text: { es: 'No para cualquiera', en: 'Not for just anyone', fr: 'Pas pour n\'importe qui' } },
    { time: 132, text: { es: '🎶', en: '🎶', fr: '🎶' } },
    { time: 156, text: { es: 'Cholita bonita, linda cusqueñita', en: 'Pretty cholita, lovely girl from Cusco', fr: 'Jolie cholita, belle fille de Cusco' } },
    { time: 159, text: { es: 'Mi dulce encanto', en: 'My sweet enchantment', fr: 'Mon doux enchantement' } },
    { time: 161, text: { es: 'Mirando, mirando tu carita', en: 'Looking, looking at your little face', fr: 'Regardant, regardant ton petit visage' } },
    { time: 165, text: { es: 'Te estoy queriendo', en: 'I am falling for you', fr: 'Je tombe amoureux de toi' } },
    { time: 167, text: { es: 'Cholita bonita, linda caneñita', en: 'Pretty cholita, lovely girl from Canas', fr: 'Jolie cholita, belle fille de Canas' } },
    { time: 170, text: { es: 'Mi dulce encanto', en: 'My sweet enchantment', fr: 'Mon doux enchantement' } },
    { time: 172, text: { es: 'Mirando, mirando tu carita', en: 'Looking, mirando ton petit visage', fr: 'Regardant, regardant ton petit visage' } },
    { time: 176, text: { es: 'Te estoy queriendo', en: 'I am falling for you', fr: 'Je tombe amoureux de toi' } },
    { time: 179, text: { es: 'Diciendo, la besaría', en: 'Saying I would kiss her', fr: 'Disant que je l\'embrasserais' } },
    { time: 181, text: { es: 'Te estoy mirando', en: 'I’m looking at you', fr: 'Je te regarde' } },
    { time: 184, text: { es: 'Me la llevaría', en: 'I would take her with me', fr: 'Je l\'emmènerais avec moi' } },
    { time: 186, text: { es: 'Te estoy dando vuelta', en: 'I am spinning around you', fr: 'Je tourne autour de toi' } },
    { time: 188, text: { es: 'Como el cóndor dando vuelta', en: 'Like a condor circling above', fr: 'Comme le condor qui tourne' } },
    { time: 191, text: { es: 'Te estoy dando vuelta', en: 'I am spinning around you', fr: 'Je tourne alrededor de toi' } },
    { time: 193, text: { es: 'Si no vas a querer', en: 'If you’re not going to love me', fr: 'Si tu ne vas pas m\'aimer' } },
    { time: 195, text: { es: 'Te voy a robar', en: 'I’m going to steal you away', fr: 'Je vais te voler' } },
    { time: 198, text: { es: 'Me vas a hacer embrujar', en: 'You’re going to put a spell on me', fr: 'Tu vas m\'ensorceler' } },
    { time: 199, text: { es: '¿O qué me vas a hacer?', en: 'Or what are you going to do to me?', fr: 'Ou que vas-tu me faire ?' } },
    { time: 201, text: { es: 'Jovencito caneño', en: 'Young man from Canas', fr: 'Jeune homme de Canas' } },
    { time: 203, text: { es: 'Mi corazón te quiere', en: 'My heart wants you', fr: 'Mon cœur te veut' } },
    { time: 205, text: { es: 'Mi cabeza te odia', en: 'My mind hates you', fr: 'Mon esprit te déteste' } },
    { time: 207, text: { es: 'Oye, travieso soltero', en: 'Hey, you mischievous bachelor', fr: 'Hé, toi célibataire espiègle' } },
    { time: 209, text: { es: 'Me vas a hacer embrujar', en: 'You’re going to put a spell on me', fr: 'Tu vas m\'ensorceler' } },
    { time: 210, text: { es: '¿O qué me vas a hacer?', en: 'Or what are you going to do to me?', fr: 'Ou que vas-tu me faire ?' } },
    { time: 212, text: { es: 'Jovencito caneño', en: 'Young man from Canas', fr: 'Jeune homme de Canas' } },
    { time: 214, text: { es: 'Mi corazón te quiere', en: 'My heart wants you', fr: 'Mon cœur te veut' } },
    { time: 216, text: { es: 'Mi cabeza te odia', en: 'My mind hates you', fr: 'Mon esprit te déteste' } },
    { time: 218, text: { es: 'Oye, travieso soltero', en: 'Hey, you mischievous bachelor', fr: 'Hé, toi célibataire espiègle' } },
    { time: 221, text: { es: 'Te quiero botar', en: 'I want to push you away', fr: 'Je veux te repousser' } },
    { time: 223, text: { es: 'Pero no puedo', en: 'But I can’t', fr: 'Mais je ne peux pas' } },
    { time: 225, text: { es: 'Me quiero ir', en: 'I want to leave', fr: 'Je veux partir' } },
    { time: 228, text: { es: 'Pero no tengo fuerzas', en: 'But I don’t have the strength', fr: 'Mais je n\'ai pas la force' } },
    { time: 230, text: { es: 'Y tú, travieso joven', en: 'And you, mischievous young man', fr: 'Et toi, jeune homme espiègle' } },
    { time: 232, text: { es: 'Estás a mi lado', en: 'You are by my side', fr: 'Tu es à mes côtés' } },
    { time: 235, text: { es: 'Las noches y las mañanas', en: 'Nights and mornings', fr: 'Les nuits et les matins' } },
    { time: 237, text: { es: 'Diciendo: te amo', en: 'Saying: I love you', fr: 'Disant : je t\'aime' } },
    { time: 239, text: { es: '🎶', en: '🎶', fr: '🎶' } },
    { time: 263, text: { es: 'Baila, hermanita', en: 'Dance, little sister', fr: 'Danse, petite sœur' } },
    { time: 265, text: { es: 'Toca, hermanito', en: 'Play, little brother', fr: 'Joue, petit frère' } },
    { time: 267, text: { es: 'En esta hermosa fiesta', en: 'At this beautiful celebration', fr: 'Dans cette belle fête' } },
    { time: 269, text: { es: 'Vamos a bailar', en: 'Let’s dance', fr: 'Allons danser' } },
    { time: 272, text: { es: 'Charango mañoso', en: 'Mischievous charango', fr: 'Charango espiègle' } },
    { time: 274, text: { es: 'Roba corazones', en: 'Heart stealer', fr: 'Voleur de cœurs' } },
    { time: 277, text: { es: 'Tú vas a tocar', en: 'You are going to play', fr: 'Tu vas jugar' } },
    { time: 279, text: { es: 'Yo voy a cantar', en: 'I am going to sing', fr: 'Je vais chanter' } },
    { time: 281, text: { es: '🎶', en: '🎶', fr: '🎶' } }
  ] },
  { id: 2, youtubeId: '58NMMld4gsk', title: 'Carnaval Solteritas', artist: 'Yeritza Corazón', languages: 'Quechua/Español',startTime: 5 },
  { id: 3, youtubeId: 'mF25iEGUmNc', title: 'Urpituchata', artist: 'Gualberto Apaza', languages: 'Quechua', startTime: 38, subtitles: [
    { time: 38, text: { es: "Una palomita había criado", en: "I had raised a little dove", fr: "J'avais élevé une petite colombe" }},
    { time: 41, text: { es: "Una palomita había criado", en: "I had raised a little dove", fr: "J'avais élevé une petite colombe" }},
    { time: 44, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 45, text: { es: "Amarradito con su cadena de oro", en: "Tied up with its golden chain", fr: "Attaché avec sa chaîne en or" }},
    { time: 48, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 50, text: { es: "Amarradito con su cadena de oro", en: "Tied up with its golden chain", fr: "Attaché avec sa chaîne en or" }},
    { time: 53, text: { es: "Aquella palomita", en: "That little dove", fr: "Cette petite colombe" }},
    { time: 54, text: { es: "Que crié", en: "That I raised", fr: "Que j'ai élevée" }},
    { time: 56, text: { es: "Aquella palomita", en: "That little dove", fr: "Cette petite colombe" }},
    { time: 57, text: { es: "Que crié", en: "That I raised", fr: "Que j'ai élevée" }},
    { time: 59, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 60, text: { es: "Me están dando ganas de irme", en: "I'm starting to feel like leaving", fr: "J'ai envie de partir" }},
    { time: 63, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 64, text: { es: "Me están dando ganas de irme", en: "I'm starting to feel like leaving", fr: "J'ai envie de partir" }},
    { time: 67, text: { es: "🎶", en: "🎶", fr: "🎶" }},
    { time: 86, text: { es: "Hubiera sabido que se iba a ir", en: "If I had known it was going to leave", fr: "Si j'avais su qu'il allait partir" }},
    { time: 92, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 93, text: { es: "Con la soga de mi burro", en: "With my donkey's rope", fr: "Avec la corde de mon âne" }},
    { time: 94, text: { es: "Lo hubiera amarrado", en: "I would have tied it up", fr: "Je l'aurais attaché" }},
    { time: 96, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 97, text: { es: "Con la soga de mi cerdo", en: "With my pig's rope", fr: "Avec la corde de mon cochon" }},
    { time: 98, text: { es: "Lo hubiera amarrado", en: "I would have tied it up", fr: "Je l'aurais attaché" }},
    { time: 101, text: { es: "Déjalo ir", en: "Let it go", fr: "Laisse-le partir" }},
    { time: 102, text: { es: "Deja que se vaya", en: "Let it leave", fr: "Laisse-le s'en aller" }},
    { time: 107, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 108, text: { es: "Solito", en: "On its own", fr: "Tout seul" }},
    { time: 109, text: { es: "Se regresará", en: "It will come back", fr: "Il reviendra" }},
    { time: 111, text: { es: "Ay, ay, ay", en: "Ay, ay, ay", fr: "Aïe, aïe, aïe" }},
    { time: 112, text: { es: "Solito", en: "On its own", fr: "Tout seul" }},
    { time: 113, text: { es: "Se devolverá", en: "It will return", fr: "Il reviendra" }},
    { time: 115, text: { es: "🎶", en: "🎶", fr: "🎶" }},
    { time: 134, text: { es: "Como el nabo", en: "Like the turnip", fr: "Comme le navet" }},
    { time: 135, text: { es: "Cuando se vuelve amarillo", en: "When it turns yellow", fr: "Quand il devient jaune" }},
    { time: 137, text: { es: "Te voy a embrujar", en: "I'm going to enchant you", fr: "Je vais t'ensorceler" }},
    { time: 138, text: { es: "Así me vas a decir", en: "That's what you'll tell me", fr: "C'est ce que tu me diras" }},
    { time: 139, text: { es: "Porque yo", en: "Because I", fr: "Parce que moi" }},
    { time: 141, text: { es: "Te haría embrujar", en: "I would have you enchanted", fr: "Je te ferais ensorceler" }},
    { time: 142, text: { es: "De la gente, su boca", en: "From people, their talk", fr: "De la bouche des gens" }},
    { time: 144, text: { es: "Te embrujará", en: "It will enchant you", fr: "Il t'ensorcellera" }},
    { time: 145, text: { es: "Tu anterior novio", en: "Your former boyfriend", fr: "Ton ancien petit ami" }},
    { time: 146, text: { es: "Te hará embrujar", en: "Will have you enchanted", fr: "Te fera ensorceler" }},
    { time: 149, text: { es: "Como el nabo", en: "Like the turnip", fr: "Comme le navet" }},
    { time: 150, text: { es: "Cuando se vuelve amarillo", en: "When it turns yellow", fr: "Quand il devient jaune" }},
    { time: 152, text: { es: "Te voy a embrujar", en: "I'm going to enchant you", fr: "Je vais t'ensorceler" }},
    { time: 153, text: { es: "Así me vas a decir", en: "That's what you'll tell me", fr: "C'est ce que tu me diras" }},
    { time: 154, text: { es: "Porque yo", en: "Because I", fr: "Parce que moi" }},
    { time: 156, text: { es: "Te haría embrujar", en: "I would have you enchanted", fr: "Je te ferais ensorceler" }},
    { time: 157, text: { es: "Tu anterior novio", en: "Your former boyfriend", fr: "Ton ancien petit ami" }},
    { time: 159, text: { es: "Te embrujará", en: "It will enchant you", fr: "Il t'ensorcellera" }},
    { time: 160, text: { es: "Tu anterior novio", en: "Your former boyfriend", fr: "Ton ancien petit ami" }},
    { time: 161, text: { es: "Te hará embrujar", en: "Will have you enchanted", fr: "Te fera ensorceler" }},
    { time: 162, text: { es: "🎶", en: "🎶", fr: "🎶" }}
  ]},
  { id: 4, youtubeId: 'RoVutuzlJS8', title: 'Ananau', artist: 'Alborada', languages: 'Quechua', startTime: 19},
  { id: 5, youtubeId: 'iaPMyWQz6cQ', title: 'Zisary Lucero', artist: 'Alborada', languages: 'Quechua' },
  { id: 6, youtubeId: 'AMKr90k6HeA', title: 'TusuyKusun', artist: 'Damaris', languages: 'Quechua/Español', startTime: 10 },
  { id: 7, youtubeId: 'y9tUqjRcuQY', title: 'Sikinanay', artist: 'Grupo Ocobamba', languages: 'Quechua/Español', startTime: 15 },
  { id: 8, youtubeId: 'TIesiNvurvM', title: 'Siqracha', artist: 'Afinación Diablo', languages: 'Quechua', startTime: 19 },
  { id: 9, youtubeId: '7VZkR-4ZAVA', title: 'Me tienes loca', artist: 'Grupo Ocobamba', languages: 'Quechua/Español', startTime: 17 },
  { id: 10, youtubeId: '8KvzZpS4E70', title: 'Enfermera', artist: 'Porfirio Ayvar', languages: 'Quechua', startTime: 33 },
  { id: 11, youtubeId: '7dci-GAE550', title: 'Carnaval Chunbivilcano', artist: 'Veronica Ccompi', languages: 'Quechua', startTime: 26, subtitles: [
    { time: 47, text: { es: 'Vamos a encontrarnos, vamos a reunirnos', en: 'Let’s meet, let’s gather', fr: 'Allons nous rencontrer, allons nous réunir' }},
    { time: 49, text: { es: 'Solterito de Chumbivilcas', en: 'single man from Chumbivilcas', fr: 'Célibataire de Chumbivilcas'}},
    { time: 51, text: { es: 'Vamos a encontrarnos, vamos a reunirnos', en: 'Let’s meet, let’s gather', fr: 'Allons nous rencontrer, allons nous réunir' }},
    { time: 54, text: { es: 'Solterito de poncho rojo', en: 'Single man in a red poncho', fr: 'Célibataire au poncho rouge'}},
    { time: 57, text: { es: 'Aqui aqui ya estoy viniendo', en: 'I\'m coming here.', fr: 'Ici, ici, je viens déjà'}},
    { time: 59, text: { es: 'Cargando el carnaval', en: 'Loading the carnival', fr: 'Chargement du carnaval'}},
    { time: 61, text: { es: 'Aqui aqui ya estoy viniendo', en: 'I\'m coming here.', fr: 'Ici, ici, je viens déjà'}},
    { time: 64, text: { es: 'Jalando el carnaval', en: 'Pulling the carnival', fr: 'Tirant le carnaval'}},
    { time: 66, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    { time: 68, text: { es: 'Yo estoy viniendo', en: 'I\'m coming', fr: 'Je viens'}},
    { time: 70, text: { es: 'señorita vivaz y solita', en: 'lively and single lady', fr: 'demoiselle vive et seule'}},
    { time: 73, text: { es: 'Yo estoy viniendo', en: 'I\'m coming', fr: 'Je viens'}},
    {time: 75, text: { es: 'joven y solita', en: 'young and alone', fr: 'jeune et seule'}},
    {time: 77, text: { es: 'En el pueblo de Chumbivilcas', en: 'In the town of Chumbivilcas', fr: 'Dans la ville de Chumbivilcas'}},
    {time: 80, text: { es: 'Una vieja como zorrillo, sombra sucia', en: 'An old woman like a skunk, dirty shadow', fr: 'Une vieille como una mouffette, ombre sale'}},
    {time: 82, text: { es: 'En el pueblo de Chumbivilcas', en: 'In the town of Chumbivilcas', fr: 'Dans la ville de Chumbivilcas'}},
    {time: 84, text: { es: 'Un viejo como zorro, sombra sucia', en: 'An old man like a fox, dirty shadow', fr: 'Un vieux como un renard, ombre sale'}},
    {time: 87, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 110, text: { es: 'Yo soy solterita', en: 'I am single', fr: 'Je suis célibataire'}},
    {time: 112, text: { es: 'Que besa a todo los jovenes', en: 'Who kisses all the young men', fr: 'Qui embrasse tous les jeunes hommes'}},
    {time: 115, text: { es: 'Yo soy jovencita dulce', en: 'I am a sweet young girl', fr: 'Je suis une douce jeune fille'}},
    {time: 117, text: { es: 'Que tumba a todos los jovenes', en: 'Who knocks down all the young men', fr: 'Qui fait tomber todos los jóvenes hombres'}},
    {time: 119, text: { es: 'Quienes son estos', en: 'Who are these', fr: 'Qui sont ceux-là'}},
    {time: 121, text: { es: 'Que no pueden con los jovenes', en: 'Who can\'t handle the young men', fr: 'Qui ne peuvent pas gérer les jóvenes hombres'}},
    {time: 124, text: { es: 'Quienes son estos', en: 'Who are these', fr: 'Qui sont ceux-là'}},
    {time: 126, text: { es: 'Que no pueden con los jovenes', en: 'Who can\'t handle the young men', fr: 'Qui ne peuvent pas gérer les jeunes hommes'}},
    {time: 129, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 131, text: { es: 'Solterito de Chumbivilcas', en: 'Bachelor from Chumbivilcas', fr: 'Célibataire de Chumbivilcas'}},
    {time: 133, text: { es: 'Vamos vamos hay que irnos', en: 'Let\'s go, we must leave', fr: 'Allons, il faut partir'}},
    {time: 136, text: { es: 'Solterito de Qolquemarca', en: 'Bachelor from Qolquemarca', fr: 'Célibataire de Qolquemarca'}},
    {time: 138, text: { es: 'Vamos vamos hay que irnos', en: 'Let\'s go, we must leave', fr: 'Allons, il faut partir'}},
    {time: 140, text: { es: 'Conmigo no mas hagamos pareja', en: 'Let\'s just be a couple with me', fr: 'Soyons juste en couple avec moi'}},
    {time: 142, text: { es: 'Conmigo no mas nos acompañaremos', en: 'Let\'s just keep each other company', fr: 'Accompagnons-nous simplement'}},
    {time: 145, text: { es: 'aunque sea bajo la lluvia hagamos pareja', en: 'even if it\'s in the rain let\'s be a couple', fr: 'même si c\'est sous la pluie soyons en couple'}},
    {time: 147, text: { es: 'incluso con granizo sigamos juntos', en: 'even with hail let\'s stay together', fr: 'même avec la grêle restons ensemble'}},
    {time: 150, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 173, text: { es: 'Hasta al joven de Chumbivilcas', en: 'Even to the young man from Chumbivilcas', fr: 'Même au jeune homme de Chumbivilcas'}},
    {time: 175, text: { es: 'De su papá le estoy repartiendo', en: 'I am distributing from his father', fr: 'Je distribue de son père'}},
    {time: 177, text: { es: 'Hasta al joven de Qolquemarca', en: 'Even to the young man from Qolquemarca', fr: 'Même au jeune homme de Qolquemarca'}},
    {time: 179, text: { es: 'De su mamá le estoy separando', en: 'I am separating him from his mother', fr: 'Je le sépare de sa mère'}},
    {time: 182, text: { es: 'Del cerro donde esta la apacheta', en: 'From the hill where the apacheta is', fr: 'De la colline où se trouve l\'apacheta'}},
    {time: 184, text: { es: 'Riendome estoy pasando ya el cerro', en: 'Laughing I am already passing the hill', fr: 'Riant je passe déjà la colline'}},
    {time: 187, text: { es: 'Hasta al joven de Qolquemarca', en: 'Even to the young man from Qolquemarca', fr: 'Même au jeune homme de Qolquemarca'}},
    {time: 189, text: { es: 'Riendome me lo estoy robando', en: 'Laughing I am stealing him', fr: 'Riant je suis en train de le voler'}},
    {time: 192, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 194, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 196, text: { es: 'Bailando le he dado vuelta', en: 'Dancing I turned him around', fr: 'Dansant je l\'ai fait tourner'}},
    {time: 199, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 201, text: { es: 'Filmando le he dado vuelta', en: 'Filming I turned him around', fr: 'Filmant je l\'ai fait tourner'}},
    {time: 203, text: { es: 'Al joven de chumbivilcas', en: 'To the young man from Chumbivilcas', fr: 'Au jeune homme de Chumbivilcas'}},
    {time: 206, text: { es: 'Llorando le estoy llevando', en: 'Crying I am taking him', fr: 'Pleurant je l\'emmène'}},
    {time: 208, text: { es: 'A su mamá y papá', en: 'To his mother and father', fr: 'À sa mère et son padre'}},
    {time: 210, text: { es: 'Les deje llorando', en: 'I left them crying', fr: 'Je les ai laissés pleurer'}},
    {time: 212, text: { es: '🎶', en: '🎶', fr: '🎶'}},
  ]},
  { id: 12, youtubeId: '2L_GlRfefWU', title: 'Chaska Ñawi Niñucha', artist: 'K\'ana wawakunas', languages: 'Quechua' },
  { id: 13, youtubeId: 'ziLjYCCo4WM', title: 'Chata Chata', artist: 'Yeritza Corazón', languages: 'Quechua', startTime: 18},
  { id: 14, youtubeId: '0vHusNucTOY', title: 'Blanca Palomita', artist: 'Veronica Ccompi', languages: 'Quechua', startTime: 32},
  { id: 15, youtubeId: 'jdWbtJYpCUM', title: 'Carnaval Cusqueño', artist: 'Veronica Ccompi', languages: 'Quechua',startTime: 20},
  { id: 16, youtubeId: '1ZDmvAy9JEs', title: 'Mueve Que Mueve Cholita', artist: 'Yeritza Corazon', languages: 'Quechua/Español',startTime: 39},
  { id: 17, youtubeId: 'MQ3z-pIwxmQ', title: 'Challwaschallay', artist: 'Apus del Perú', languages: 'Quechua/Subtitle',startTime: 27, subtitles: [
    {time: 41, text: { es: 'De río en río', en: 'From river to river', fr: 'De rivière en rivière'}},
    {time: 42, text: { es: 'Voy caminando', en: 'I walk along', fr: 'Je marche'}},
    {time: 44, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 46, text: { es: 'Ya no te encuentro', en: 'I can no longer find you', fr: 'Je ne te trouve plus'}},

    {time: 48, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 50, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 52, text: { es: 'Más al contrario', en: 'On the contrary', fr: 'Au contraire'}},
    {time: 54, text: { es: 'Te recuerdo', en: 'I remember you', fr: 'Je me souviens de toi'}},

    {time: 56, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 57, text: { es: 'Recordando tu nombre', en: 'Remembering your name', fr: 'En me souvenant de ton nom'}},
    {time: 60, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 62, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},

    {time: 64, text: { es: '🎶', en: '🎶', fr: '🎶'}},

    {time: 92, text: { es: 'Regrésate', en: 'Come back', fr: 'Reviens'}},
    {time: 93, text: { es: 'Devuélvete', en: 'Turn back', fr: 'Retourne'}},
    {time: 95, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 97, text: { es: 'Aunque sea para mirar la luna', en: 'Even if just to look at the moon', fr: 'Même si c’est juste pour regarder la lune'}},

    {time: 99, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 104, text: { es: 'Tu palomita', en: 'Your little dove', fr: 'Ta petite colombe'}},
    {time: 105, text: { es: 'Te está esperando', en: 'Is waiting for you', fr: 'T’attend'}},

    {time: 107, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},
    {time: 108, text: { es: 'Porque te quiero', en: 'Because I love you', fr: 'Parce que je t’aime'}},
    {time: 110, text: { es: 'Te estoy buscando', en: 'I am looking for you', fr: 'Je te cherche'}},
    {time: 111, text: { es: 'Mi pescadito', en: 'My little fish', fr: 'Mon petit poisson'}},

    {time: 117, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},
    {time: 121, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},

    {time: 123, text: { es: 'De río en río', en: 'From river to river', fr: 'De rivière en rivière'}},
    {time: 124, text: { es: 'Haciéndome caminar', en: 'Making me walk', fr: 'Me faisant marcher'}},
    {time: 126, text: { es: 'De casa en casa', en: 'From house to house', fr: 'De maison en maison'}},
    {time: 127, text: { es: 'Haciéndome buscarte', en: 'Making me look for you', fr: 'Me faisant te chercher'}},

    {time: 130, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},
    {time: 133, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},

    {time: 135, text: { es: 'De río en río', en: 'From river to river', fr: 'De rivière en rivière'}},
    {time: 136, text: { es: 'Haciéndome caminar', en: 'Making me walk', fr: 'Me faisant marcher'}},
    {time: 139, text: { es: 'De casa en casa', en: 'From house to house', fr: 'De maison en maison'}},
    {time: 140, text: { es: 'Haciéndome buscarte', en: 'Making me look for you', fr: 'Me faisant te chercher'}},

    {time: 142, text: { es: '🎶', en: '🎶', fr: '🎶'}},

    {time: 166, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},
    {time: 169, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},

    {time: 171, text: { es: 'De río en río', en: 'From river to river', fr: 'De rivière en rivière'}},
    {time: 172, text: { es: 'Haciéndome caminar', en: 'Making me walk', fr: 'Me faisant marcher'}},
    {time: 174, text: { es: 'De casa en casa', en: 'From house to house', fr: 'De maison en maison'}},
    {time: 175, text: { es: 'Haciéndome buscarte', en: 'Making me look for you', fr: 'Me faisant te chercher'}},

    {time: 178, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},
    {time: 181, text: { es: '¿Con gusto estarás caminando?', en: 'Are you walking happily?', fr: 'Marches-tu avec plaisir ?'}},

    {time: 183, text: { es: 'De río en río', en: 'From river to river', fr: 'De rivière en rivière'}},
    {time: 184, text: { es: 'Haciéndome caminar', en: 'Making me walk', fr: 'Me faisant marcher'}},
    {time: 187, text: { es: 'De casa en casa', en: 'From house to house', fr: 'De maison en maison'}},
    {time: 188, text: { es: 'Haciéndome buscarte', en: 'Making me look for you', fr: 'Me faisant te chercher'}},

    {time: 189, text: { es: '🎶', en: '🎶', fr: '🎶'}},
  ]},
  { id: 18, youtubeId: 'wpIrEmUWL9Q', title: 'Chachacomaschay', artist: 'Rosita de Espinar', languages: 'Quechua',startTime: 40},
  { id: 19, youtubeId: '7a8a0Jzf00M', title: 'Chachacomaschay', artist: 'Ricardina Rayme', languages: 'Quechua',startTime: 30},
  { id: 20, youtubeId: '_JwzS6_V_W0', title: 'Taxichalla', artist: 'Rosita de Espinar', languages: 'Quechua',startTime: 23},
  { id: 21, youtubeId: '-GtToBsC3GE', title: 'Maypirac Tragucha', artist: 'Illary Del Cusco', languages: 'Quechua/Español',startTime: 40},
  { id: 22, youtubeId: 'GcWmgKH8A5Y', title: 'Urcos Plazachapi', artist: 'Condemayta de Acomayo', languages: 'Quechua',startTime: 27},
  { id: 23, youtubeId: 'R3nVncDD8VY', title: 'Eucaliptucha', artist: 'Acomaino Comerciante', languages: 'Quechua/Subtitle',startTime: 30, subtitles: [
    {time: 30, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 32, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 34, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 36, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},

    {time: 38, text: { es: 'A mi primer amor', en: 'To my first love', fr: 'À mon premier amour'}},
    {time: 40, text: { es: 'No lo hubieras igualado', en: 'You could not have matched him/her', fr: 'Tu n’aurais pas pu l’égaler'}},
    {time: 43, text: { es: 'A mi primer amor', en: 'To my first love', fr: 'À mon premier amour'}},
    {time: 44, text: { es: 'No lo hubieras igualado', en: 'You could not have matched him/her', fr: 'Tu n’aurais pas pu l’égaler'}},

    {time: 46, text: { es: '🎶', en: '🎶', fr: '🎶'}},

    {time: 65, text: { es: 'Lo hubieras igualado', en: 'You could have matched him/her', fr: 'Tu aurais pu l’égaler'}},
    {time: 66, text: { es: 'Lo hubieras comparado', en: 'You could have compared him/her', fr: 'Tu aurais pu le/la comparer'}},
    {time: 69, text: { es: 'Lo hubieras igualado', en: 'You could have matched him/her', fr: 'Tu aurais pu l’égaler'}},
    {time: 71, text: { es: 'Lo hubieras comparado', en: 'You could have compared him/her', fr: 'Tu aurais pu le/la comparer'}},

    {time: 73, text: { es: 'Lo que comía en la cima', en: 'What he/she ate at the top', fr: 'Ce qu’il/elle mangeait au sommet'}},
    {time: 75, text: { es: 'Qué vas a saber lo que comía', en: 'How would you know what he/she ate', fr: 'Comment saurais-tu ce qu’il/elle mangeait'}},
    {time: 77, text: { es: 'Lo que dormía en la cama', en: 'How he/she slept in bed', fr: 'Comment il/elle dormait dans le lit'}},
    {time: 79, text: { es: 'Qué vas a saber cómo dormía', en: 'How would you know how he/she slept', fr: 'Comment saurais-tu comment il/elle dormait'}},

    {time: 82, text: { es: '🎶', en: '🎶', fr: '🎶'}},

    {time: 100, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 102, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 104, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},
    {time: 106, text: { es: 'Eucalipto', en: 'Eucalyptus', fr: 'Eucalyptus'}},

    {time: 108, text: { es: 'A mi primer amor', en: 'To my first love', fr: 'À mon premier amour'}},
    {time: 110, text: { es: 'No lo hubieras igualado', en: 'You could not have matched him/her', fr: 'Tu n’aurais pas pu l’égaler'}},
    {time: 113, text: { es: 'A mi primer amor', en: 'To my first love', fr: 'À mon premier amour'}},
    {time: 114, text: { es: 'No lo hubieras igualado', en: 'You could not have matched him/her', fr: 'Tu n’aurais pas pu l’égaler'}},

    {time: 117, text: { es: '🎶', en: '🎶', fr: '🎶'}},

    {time: 148, text: { es: 'Ay, tostonchay', en: 'Oh, my dear Tostonchay', fr: 'Oh, mon cher Tostonchay'}},
    {time: 149, text: { es: 'Tostonchay', en: 'Tostonchay', fr: 'Tostonchay'}},
    {time: 150, text: { es: 'De mi mamá no es para su gusto', en: 'It’s not to my mother’s liking', fr: 'Ce n’est pas au goût de ma mère'}},
    {time: 153, text: { es: 'Mi gusto es primero', en: 'My choice comes first', fr: 'Mon choix passe en premier'}},

    {time: 155, text: { es: 'Con quién, con cuál estaré', en: 'Who and where will I be with', fr: 'Avec qui et où serai-je'}},
    {time: 157, text: { es: 'Con quién, con cuál estaré', en: 'Who and where will I be with', fr: 'Avec qui et où serai-je'}},

    {time: 160, text: { es: 'Ay, tostonchay', en: 'Oh, my dear Tostonchay', fr: 'Oh, mon cher Tostonchay'}},
    {time: 161, text: { es: 'Tostonchay', en: 'Tostonchay', fr: 'Tostonchay'}},
    {time: 163, text: { es: 'De mi mamá no es para su gusto', en: 'It’s not to my mother’s liking', fr: 'Ce n’est pas au goût de ma mère'}},
    {time: 165, text: { es: 'Mi gusto es primero', en: 'My choice comes first', fr: 'Mon choix passe en premier'}},

    {time: 167, text: { es: 'Con quién, con cuál estaré', en: 'Who and where will I be with', fr: 'Avec qui et où serai-je'}},
    {time: 170, text: { es: 'Con quién, con cuál estaré', en: 'Who and where will I be with', fr: 'Avec qui et où serai-je'}},

    {time: 173, text: { es: '🎶', en: '🎶', fr: '🎶'}},
  ]},
  { id: 24, youtubeId: 'fpUeQO151Vw', title: 'Mix Kempor de Cusipata', artist: 'Afinación Diablo', languages: 'Quechua',startTime: 30},
  { id: 25, youtubeId: 'ggnoG5S_VNU', title: 'Cuerpo soltero', artist: 'Condemayta de Acomayo', languages: 'Quechua/Español',startTime: 18},
  { id: 26, youtubeId: 'crJdcHcKbgM', title: 'Kaychu Buena vida', artist: 'Afinación Diablo', languages: 'Quechua',startTime: 18},
  { id: 27, youtubeId: 'MDazdh7FGMw', title: 'Ichucha Mana Mamayoc', artist: 'Siwina de Accha', languages: 'Quechua',startTime: 17},
  { id: 28, youtubeId: 'J4FZ9Tpeuqg', title: 'Cabra Q\'aracha', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 50, subtitles: [
    {time: 52, text: { es: 'Por ser pobre, por ser humilde', en: 'For being poor, for being humble', fr: 'Pour être pauvre, pour être humble'}},
    {time: 55, text: { es: 'Te hice dormir en el cuero de la cabra', en: 'I made you sleep on the goat skin', fr: 'Je t\'ai fait dormir sur la peau de chèvre'}},
    {time: 58, text: { es: 'Por ser pobre, por ser humilde', en: 'For being poor, for being humble', fr: 'Pour être pauvre, pour être humble'}},
    {time: 60, text: { es: 'Te hice dormir en el cuero de la cabra', en: 'I made you sleep on the goat skin', fr: 'Je t\'ai fait dormir sur la peau de chèvre'}},
    {time: 64, text: { es: 'El cuero de la cabra', en: 'The goat skin', fr: 'La peau de chèvre'}},
    {time: 65, text: { es: 'Tampoco era mio', en: 'It wasn\'t mine either', fr: 'Ce n\'était pas à moi non plus'}},
    {time: 66, text: { es: 'Es lo que me preste de mi vecina', en: 'It\'s what I borrowed from my neighbor', fr: 'C\'est ce que j\'ai emprunté à ma voisine'}},
    {time: 69, text: { es: 'De mi vecina', en: 'From my neighbor', fr: 'De ma voisine'}},
    {time: 70, text: { es: 'Tampoco es', en: 'It isn\'t either', fr: 'Ce n\'est pas non plus'}},
    {time: 71, text: { es: 'Lo que se prestó de la hacienda', en: 'It\'s what came from the estate', fr: 'C\'est ce qui a été emprunté au domaine'}},
    {time: 74, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 99, text: { es: 'De la asienda', en: 'From the estate', fr: 'De la propiedad'}},
    {time: 100, text: { es: 'Tampoco es', en: 'It isn\'t either', fr: 'Ce n\'est pas non plus'}},
    {time: 102, text: { es: 'Lo que lo quitaron del hervajero', en: 'What they took from the herbalist', fr: 'Ce qu\'ils ont pris à l\'herboriste'}},
    {time: 105, text: { es: 'De la asienda', en: 'From the estate', fr: 'De la propiedad'}},
    {time: 106, text: { es: 'Tampoco es', en: 'It isn\'t either', fr: 'Ce n\'est pas non plus'}},
    {time: 107, text: { es: 'Es lo que se prestaron del hevajero', en: 'It\'s what was borrowed from the herbalist', fr: 'C\'est ce qui a été emprunté à l\'herboriste'}},
    {time: 110, text: { es: 'Del hervajero', en: 'From the herbalist', fr: 'De l\'herboriste'}},
    {time: 111, text: { es: 'Tampoco es', en: 'It isn\'t either', fr: 'Ce n\'est pas non plus'}},
    {time: 112, text: { es: 'Es lo que le quito del zorrito', en: 'It\'s what was taken from the little fox', fr: 'C\'est ce qui a été pris au petit renard'}},
    {time: 116, text: { es: 'Del hervajero', en: 'From the herbalist', fr: 'De l\'herboriste'}},
    {time: 117, text: { es: 'Tampoco es', en: 'It isn\'t either', fr: 'Ce n\'est pas non plus'}},
    {time: 118, text: { es: 'Es lo que le quito del zorrito', en: 'It\'s what was taken from the little fox', fr: 'C\'est ce qui a été pris au petit renard'}},
    {time: 120, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 146, text: { es: 'Por tu carita no mas', en: 'Just for your little face', fr: 'Juste pour ton petit visage'}},
    {time: 147, text: { es: 'Te estoy rondando', en: 'I am hanging around you', fr: 'Je rode autour de toi'}},
    {time: 150, text: { es: 'Por tu ojos negros', en: 'For your black eyes', fr: 'Pour tes ojos negros'}},
    {time: 151, text: { es: 'Te estoy mirando', en: 'I am looking at you', fr: 'Je te regarde'}},
    {time: 153, text: { es: 'Te estoy rondando', en: 'I am hanging around you', fr: 'Je rode autour de toi'}},
    {time: 156, text: { es: 'Por tu carita no mas', en: 'Just for your little face', fr: 'Juste pour ton petit visage'}},
    {time: 157, text: { es: 'Te estoy rondando', en: 'I am hanging around you', fr: 'Je rode autour de toi'}},
    {time: 160, text: { es: 'Por tu ojos negros', en: 'For your black eyes', fr: 'Pour tes ojos negros'}},
    {time: 161, text: { es: 'Te estoy mirando', en: 'I am looking at you', fr: 'Je te regarde'}},
    {time: 163, text: { es: 'Te estoy rondando', en: 'I am hanging around you', fr: 'Je rode autour de toi'}},
    {time: 166, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    
  ]},
  { id: 29, youtubeId: 'c6pJ7C9ioOs', title: 'Sisascha', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 15},
  { id: 30, youtubeId: '9u7pcM7e9D8', title: 'Qhayna Nihuranki', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 15},
  { id: 31, youtubeId: 'R1HhY5XIeF4', title: 'AY URPICHAY URPI', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 15},
  { id: 32, youtubeId: 'XfL7NCINiMg', title: 'Carnaval Traicionera', artist: 'Roger Chino', languages: 'Quechua/Subtitle',startTime: 15, subtitles:[
    {time: 36, text: { es: "Por las lomas he caminado", en: "Over the hills I have walked", fr: "Par les collines j'ai marché"}},
    {time: 39, text: { es: "Mirando a todas las chicas", en: "Looking at all the girls", fr: "En regardant toutes les filles"}},
    {time: 42, text: { es: "Por la loma que he caminado", en: "Along the hill where I have walked", fr: "Sur la colline où j'ai marché"}},
    {time: 44, text: { es: "Con esta soltera me encontré", en: "With this single woman I met", fr: "J'ai rencontré cette femme célibataire"}},
    {time: 46, text: { es: "Con una traicionera me encontré", en: "With a treacherous woman I met", fr: "J'ai rencontré une femme traîtresse"}},
    {time: 50, text: { es: "A la traicionera mujer", en: "To the treacherous woman", fr: "À la femme traîtresse"}},
    {time: 50, text: { es: "Dando vueltas le doy zancadillas", en: "Spinning around, I trip her up", fr: "En tournant, je lui fais des croche-pieds"}},
    {time: 54, text: { es: "A una mujer cualquiera", en: "To any ordinary woman", fr: "À n'importe quelle femme"}},
    {time: 57, text: { es: "Haciéndolas gritar las he echado", en: "Making them scream, I've cast them out", fr: "En les faisant crier, je les ai jetées"}},
    {time: 60, text: { es: "A la traicionera mujer", en: "To the treacherous woman", fr: "À la femme traîtresse"}},
    {time: 62, text: { es: "Dándole vueltas la he dejado", en: "Spinning her around, I have left her", fr: "En la faisant tourner, je l'ai laissée"}},
    {time: 65, text: { es: "A una mujer cualquiera", en: "To any ordinary woman", fr: "À n'importe quelle femme"}},
    {time: 65, text: { es: "Haciéndolas gritar las he echado", en: "Making them scream, I've cast them out", fr: "En les faisant crier, je les ai jetées"}},
    {time: 70, text: { es: "Por la loma he venido", en: "Over the hill I have come", fr: "Par la colline je suis venu"}},
    {time: 73, text: { es: "Para buscarme un joven", en: "To look for a young man", fr: "Pour me chercher un jeune homme"}},
    {time: 75, text: { es: "Que voy a encontrar", en: "That I am going to find", fr: "Que je vais trouver"}},
    {time: 78, text: { es: "Me encontré con un traicionero", en: "I met a treacherous man", fr: "J'ai rencontré un homme traître"}},
    {time: 80, text: { es: "Con alguien ordinario me encontré", en: "I met someone ordinary", fr: "J'ai rencontré quelqu'un de banal"}},
    {time: 83, text: { es: "Al joven traicionero", en: "To the treacherous young man", fr: "Au jeune homme traître"}},
    {time: 86, text: { es: "Dando vueltas le doy zancadillas", en: "Spinning around, I trip him up", fr: "En tournant, je lui fais des croche-pieds"}},
    {time: 88, text: { es: "A un joven cualquiera", en: "To any ordinary young man", fr: "À n'importe quel jeune homme"}},
    {time: 91, text: { es: "A mitad del camino lo echo", en: "Halfway through, I cast him out", fr: "À mi-chemin, je le jette"}},
    {time: 94, text: { es: "Al joven traicionero", en: "To the treacherous young man", fr: "Au jeune homme traître"}},
    {time: 96, text: { es: "Dando vueltas le doy zancadillas", en: "Spinning around, I trip him up", fr: "En tournant, je lui fais des croche-pieds"}},
    {time: 99, text: { es: "A un joven cualquiera", en: "To any ordinary young man", fr: "À n'importe quel jeune homme"}},
    {time: 101, text: { es: "A mitad del camino lo echo", en: "Halfway through, I cast him out", fr: "À mi-chemin, je le jette"}},
    {time: 104, text: { es: "Serías solterita", en: "You might be single", fr: "Tu serais célibataire"}},
    {time: 107, text: { es: "Serías manzanita", en: "You might be a little apple", fr: "Tu serais une petite pomme"}},
    {time: 109, text: { es: "A ver, te voy a probar", en: "Let's see, I'm going to test you", fr: "Voyons voir, je vais t'essayer"}},
    {time: 112, text: { es: "Parece que tienes marido", en: "It seems you have a husband", fr: "On dirait que tu as un mari"}},
    {time: 114, text: { es: "Parece que tienes un hijo", en: "It seems you have a child", fr: "On dirait que tu as un enfant"}},
    {time: 117, text: { es: "Si eres una mujer con marido", en: "If you are a woman with a husband", fr: "Si tu es une femme avec un mari"}},
    {time: 120, text: { es: "Atiende a tu marido", en: "Take care of your husband", fr: "Prends soin de ton mari"}},
    {time: 122, text: { es: "Si eres una mujer con hijo", en: "If you are a woman with a child", fr: "Si tu es une femme avec un enfant"}},
    {time: 125, text: { es: "Amamanta todavía a tu hijo", en: "Still breastfeed your child", fr: "Allaite encore ton enfant"}},
    {time: 128, text: { es: "Si eres una mujer con marido", en: "If you are a woman with a husband", fr: "Si tu es une femme avec un mari"}},
    {time: 130, text: { es: "Atiende a tu marido", en: "Take care of your husband", fr: "Prends soin de ton mari"}},
    {time: 133, text: { es: "Si eres una mujer con hijo", en: "If you are a woman with a child", fr: "Si tu es une femme avec un enfant"}},
    {time: 135, text: { es: "Amamanta todavía a tu hijo", en: "Still breastfeed your child", fr: "Allaite encore ton enfant"}},
    {time: 138, text: { es: "Te has hecho pasar por soltero", en: "You have pretended to be single", fr: "Tu t'es fait passer pour célibataire"}},
    {time: 140, text: { es: "Te has quedado solito", en: "You have ended up all alone", fr: "Tu t'es retrouvé tout seul"}},
    {time: 143, text: { es: "¿Qué clase de soltero serás?", en: "What kind of single man will you be?", fr: "Quel genre de célibataire seras-tu ?"}},
    {time: 145, text: { es: "Varias mujeres habías tenido", en: "Several women you had kept", fr: "Plusieurs femmes tu avais eues"}},
    {time: 148, text: { es: "Para no quererte", en: "Not to love you", fr: "Pour ne pas t'aimer"}},
    {time: 149, text: { es: "Habías sido", en: "You had been", fr: "Tu avais été"}},
    {time: 151, text: { es: "Si eres un joven soltero", en: "If you are a young single man", fr: "Si tu es un jeune célibataire"}},
    {time: 153, text: { es: "Cómprame una cerveza", en: "Buy me a beer", fr: "Achète-moi une bière"}},
    {time: 153, text: { es: "Si eres un joven con mujer", en: "If you are a young man with a woman", fr: "Si tu es un jeune homme avec une femme"}},
    {time: 158, text: { es: "Atiende a tu mujer", en: "Take care of your woman", fr: "Prends soin de ta femme"}},
    {time: 161, text: { es: "Si eres un joven soltero", en: "If you are a young single man", fr: "Si tu es un jeune célibataire"}},
    {time: 164, text: { es: "Cómprame una cerveza", en: "Buy me a beer", fr: "Achète-moi une bière"}},
    {time: 166, text: { es: "Si eres un joven con mujer", en: "If you are a young man with a woman", fr: "Si tu es un jeune homme avec une femme"}},
    {time: 169, text: { es: "Atiende a tu mujer", en: "Take care of your woman", fr: "Prends soin de ta femme"}},
    {time: 172, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 192, text: { es: "¡Ay, guitarra, guitarra!", en: "Oh, guitar, guitar!", fr: "Ah, guitare, guitare !"}},
    {time: 195, text: { es: "Guitarra de madera, corazón", en: "Wooden guitar, sweetheart", fr: "Guitare en bois, mon cœur"}},
    {time: 197, text: { es: "Con nuestro dulce tocar", en: "With our sweet playing", fr: "Avec notre doux jeu"}},
    {time: 200, text: { es: "Todas las solteras vendrán", en: "All the single women will come", fr: "Toutes les célibataires viendront"}},
    {time: 202, text: { es: "Hasta con sus hermanas van a venir", en: "They'll even come with their sisters", fr: "Elles viendront même avec leurs sœurs"}},
    {time: 205, text: { es: "Una para ser mi cocinera", en: "One to be my cook", fr: "Une pour être ma cuisinière"}},
    {time: 208, text: { es: "Una para ser mi lavandera", en: "One to be my washerwoman", fr: "Une pour être ma blanchisseuse"}},
    {time: 210, text: { es: "Una para ser mi compañera de cama", en: "One to be my sleeping partner", fr: "Une pour être ma compagne de lit"}},
    {time: 212, text: { es: "Una para ser mi compañera de canto", en: "One to be my singing partner", fr: "Une pour être ma compagne de chant"}},
    {time: 215, text: { es: "Una para ser mi lavandera", en: "One to be my washerwoman", fr: "Une pour être ma blanchisseuse"}},
    {time: 218, text: { es: "Una para ser mi cocinera", en: "One to be my cook", fr: "Une pour être ma cuisinière"}},
    {time: 220, text: { es: "Una para ser mi compañera de cama", en: "One to be my sleeping partner", fr: "Une pour être ma compagne de lit"}},
    {time: 223, text: { es: "Una para ser mi compañera de canto", en: "One to be my singing partner", fr: "Une pour être ma compagne de chant"}},
    {time: 226, text: { es: "¡Ay, charango, charango!", en: "Oh, charango, charango!", fr: "Ah, charango, charango !"}},
    {time: 228, text: { es: "Charango de madera, corazón", en: "Wooden charango, sweetheart", fr: "Charango en bois, mon cœur"}},
    {time: 231, text: { es: "Con nuestro dulce tocar", en: "With our sweet playing", fr: "Avec notre doux jeu"}},
    {time: 233, text: { es: "Hasta a su hermano encontraremos", en: "We'll even find their brother", fr: "On trouvera même son frère"}},
    {time: 235, text: { es: "Hasta a su hermano menor encontraremos", en: "We'll even find their younger brother", fr: "On trouvera même son petit frère"}},
    {time: 239, text: { es: "Uno para que trabaje en la chacra", en: "One to work the fields", fr: "Un pour travailler aux champs"}},
    {time: 241, text: { es: "Uno para pastorear mis animales", en: "One to herd my animals", fr: "Un pour faire paître mes animaux"}},
    {time: 244, text: { es: "Uno para ser mi compañero de cama", en: "One to be my sleeping partner", fr: "Un pour être mon compagnon de lit"}},
    {time: 246, text: { es: "Uno para ser mi compañero de canto", en: "One to be my singing partner", fr: "Un pour être mon compagnon de chant"}},
    {time: 249, text: { es: "Uno para que trabaje en la chacra", en: "One to work the land", fr: "Un pour travailler la terre"}},
    {time: 251, text: { es: "Uno para pastorear mis animales", en: "One to herd my animals", fr: "Un pour faire paître mes animaux"}},
    {time: 254, text: { es: "Uno para ser mi compañero de cama", en: "One to be my sleeping partner", fr: "Un pour être mon compagnon de lit"}},
    {time: 256, text: { es: "Uno para ser mi compañero de canto", en: "One to be my singing partner", fr: "Un pour être mon compagnon de chant"}},
    {time: 259, text: { es: "Si tú me quieres, cholita", en: "If you love me, girl", fr: "Si tu m'aimes, fillette"}},
    {time: 262, text: { es: "Si tú me amas, bonita", en: "If you love me, pretty one", fr: "Si tu m'aimes, ma belle"}},
    {time: 264, text: { es: "Demuéstrame tu cariño", en: "Show me your affection", fr: "Montre-moi ton affection"}},
    {time: 266, text: { es: "Prueba de tu sentimiento", en: "Proof of your feelings", fr: "Preuve de tes sentiments"}},
    {time: 269, text: { es: "Prueba de tu amor profundo", en: "Proof of your deep love", fr: "Preuve de ton amour profond"}},
    {time: 272, text: { es: "Si tú me quieres, cholita", en: "If you love me, girl", fr: "Si tu m'aimes, fillette"}},
    {time: 275, text: { es: "Una buena vida viviremos", en: "A good life we shall live", fr: "Une bonne vie nous vivrons"}},
    {time: 277, text: { es: "Si así me quieres, bonita", en: "If you love me so, pretty one", fr: "Si tu m'aimes ainsi, ma belle"}},
    {time: 280, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 282, text: { es: "Si tú me quieres, cholita", en: "If you love me, girl", fr: "Si tu m'aimes, fillette"}},
    {time: 285, text: { es: "Una buena vida pasaremos", en: "A good life we shall have", fr: "Une bonne vie nous passerons"}},
    {time: 287, text: { es: "Si así me quieres, bonita", en: "If you love me so, pretty one", fr: "Si tu m'aimes ainsi, ma belle"}},
    {time: 290, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 293, text: { es: "Si tú me quieres, cholito", en: "If you love me, boy", fr: "Si tu m'aimes, garçon"}},
    {time: 295, text: { es: "Si tú me amas, chinito", en: "If you love me, darling", fr: "Si tu m'aimes, chéri"}},
    {time: 298, text: { es: "Demuéstrame tu cariño", en: "Show me your affection", fr: "Montre-moi ton affection"}},
    {time: 300, text: { es: "Prueba de tu sentimiento", en: "Proof of your feelings", fr: "Preuve de tes sentiments"}},
    {time: 303, text: { es: "Prueba de tu amor profundo", en: "Proof of your deep love", fr: "Preuve de ton amour profond"}},
    {time: 306, text: { es: "Si es verdad que tú me quieres", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 308, text: { es: "Una buena vida pasaremos", en: "A good life we shall have", fr: "Une bonne vie nous passerons"}},
    {time: 311, text: { es: "Si es verdad que tú me amas", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 313, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 316, text: { es: "Si es verdad que tú me quieres", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 318, text: { es: "Una buena vida pasaremos", en: "A good life we shall have", fr: "Une bonne vie nous passerons"}},
    {time: 321, text: { es: "Si es verdad que tú me amas", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 323, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 326, text: { es: '🎶', en: '🎶', fr: '🎶'}},
    {time: 347, text: { es: "Si es verdad que tú me quieres", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 349, text: { es: "Una buena vida pasaremos", en: "A good life we shall have", fr: "Une bonne vie nous passerons"}},
    {time: 352, text: { es: "Si es verdad que tú me amas", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 354, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 357, text: { es: "Si es verdad que tú me quieres", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 359, text: { es: "Una buena vida pasaremos", en: "A good life we shall have", fr: "Une bonne vie nous passerons"}},
    {time: 362, text: { es: "Si es verdad que tú me amas", en: "If it's true that you love me", fr: "S'il est vrai que tu m'aimes"}},
    {time: 364, text: { es: "Una buena vida disfrutaremos", en: "A good life we shall enjoy", fr: "Une bonne vie nous apprécierons"}},
    {time: 367, text: { es: '🎶', en: '🎶', fr: '🎶'}},
  ]},
  { id: 33, youtubeId: 'fmx_x2rwMIQ', title: 'SUEGRA MALDITA', artist: 'Gualberto Apaza', languages: 'Quechua/Español',startTime: 20},
  { id: 34, youtubeId: 'SNRif7ujbBM', title: 'MARIACHA', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 15},
  { id: 35, youtubeId: 'WMNOllvIFnE', title: 'AVIONCHA', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 20},
  { id: 36, youtubeId: 'hQcIwmtJ1cY', title: 'SIRENITA', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 11},
  { id: 37, youtubeId: 'd8g6x-SGQVU', title: 'BORRACHO', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 29},
  { id: 38, youtubeId: 'xWQMXx6nkco', title: 'VERDE VIOLETA', artist: 'Gualberto Apaza', languages: 'Quechua',startTime: 20},
  { id: 39, youtubeId: 'adxbfuFiDb4', title: 'Soltera Warmi', artist: 'Gato Del Arpa', languages: 'Quechua',startTime: 24},
  { id: 40, youtubeId: 'FBbd2Jqgidg', title: 'Chiririnkacha', artist: 'Gato Del Arpa', languages: 'Quechua',startTime: 35},
  { id: 41, youtubeId: 'PPjg86WxD4s', title: 'Cerveza tomasqay', artist: 'Ccasita Record', languages: 'Quechua',startTime: 30},
  { id: 42, youtubeId: 'TwWlkbM5nPQ', title: 'Chiwillituy', artist: 'Ayrampito', languages: 'Quechua',startTime: 18},
];